### ISSUE TITLE
Trouble reproducing the desired output

### ISSUE THREAD

**Issue by GuidoGuberman** [basjacobs93/limosa#1]
Hi Bas,

I am trying to use your code to display images of brain areas when hovering over a heatmap that contains brain-related data. Having been unable to do it, I tried instead running your Rmd script. The only thing I modified was the directory that contained the images to display. Still, the last figure does not display the images when hovering over the points. At this point, I would just like to get your advice to understand what it is that I'm doing wrong.

Thank you,
Guido.

**Comment by basjacobs93** [comment]
Hi Guido,

Thanks for reaching out!

Often when this happens, it means the location where the files are is not reachable from the location where the plotly html is saved. The best way to debug this is by opening the plot in your browser (for example via the 'Show in new window' button in RStudio), and open the browser console to look for errors. In the JavaScript code you can add `console.log()` statements to help you debug.

By default, RStudio uses a temporary folder to store these generated html files in. You can find this with `tempdir()`. Try placing your images there and adjust the javascript to point to that (relative) path: `image_location = '../' + txt + '.jpg';`.

A second issue that could arise is that your browser blocks the requests for the images. If that's the case, try a different browser or use a fix like the ones proposed [here](https://stackoverflow.com/questions/39007243/cannot-open-local-file-chrome-not-allowed-to-load-local-resource).

Best of luck!

Bas

**Comment by GuidoGuberman** [comment]
Thanks for your help Bas! Unfortunately, I was not able to get it to work, I ended up going with another solution using Shiny Apps. But I appreciate your response nonetheless.
Guido.
